// <auto-generated />
using KnittyGritty.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KnittyGritty.Migrations
{
    [DbContext(typeof(KnittyGrittyContext))]
    [Migration("20260326142442_RecreatePatternYarn")]
    partial class RecreatePatternYarn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KnittyGritty.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("KnittyGritty.Models.Designer", b =>
                {
                    b.Property<int>("DesignerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DesignerID"));

                    b.Property<string>("Alias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Handle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DesignerID");

                    b.ToTable("Designer");
                });

            modelBuilder.Entity("KnittyGritty.Models.Language", b =>
                {
                    b.Property<int>("LanguageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LanguageID"));

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LanguageID");

                    b.ToTable("Language");
                });

            modelBuilder.Entity("KnittyGritty.Models.Pattern", b =>
                {
                    b.Property<int>("PatternID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatternID"));

                    b.Property<string>("Craft")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DesignerID")
                        .HasColumnType("int");

                    b.Property<string>("Difficulty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Gauge")
                        .HasColumnType("real");

                    b.Property<string>("GaugePattern")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MultipleStrands")
                        .HasColumnType("bit");

                    b.Property<float>("Needles")
                        .HasColumnType("real");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverallYarnWeight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatternType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatternID");

                    b.HasIndex("DesignerID");

                    b.ToTable("Pattern");
                });

            modelBuilder.Entity("KnittyGritty.Models.PatternCategory", b =>
                {
                    b.Property<int>("PatternID")
                        .HasColumnType("int");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.HasKey("PatternID", "CategoryID");

                    b.HasIndex("CategoryID");

                    b.ToTable("PatternCategory");
                });

            modelBuilder.Entity("KnittyGritty.Models.PatternLanguage", b =>
                {
                    b.Property<int>("PatternID")
                        .HasColumnType("int");

                    b.Property<int>("LanguageID")
                        .HasColumnType("int");

                    b.HasKey("PatternID", "LanguageID");

                    b.HasIndex("LanguageID");

                    b.ToTable("PatternLanguage");
                });

            modelBuilder.Entity("KnittyGritty.Models.PatternSize", b =>
                {
                    b.Property<int>("PatternID")
                        .HasColumnType("int");

                    b.Property<int>("SizeID")
                        .HasColumnType("int");

                    b.Property<int>("Circumference")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatternID", "SizeID");

                    b.HasIndex("SizeID");

                    b.ToTable("PatternSize");
                });

            modelBuilder.Entity("KnittyGritty.Models.PatternSizeYarn", b =>
                {
                    b.Property<int>("PatternID")
                        .HasColumnType("int");

                    b.Property<int>("SizeID")
                        .HasColumnType("int");

                    b.Property<int>("YarnID")
                        .HasColumnType("int");

                    b.Property<int>("MeterageUsage")
                        .HasColumnType("int");

                    b.Property<float>("SkeinUsage")
                        .HasColumnType("real");

                    b.HasKey("PatternID", "SizeID", "YarnID");

                    b.HasIndex("SizeID");

                    b.HasIndex("YarnID");

                    b.ToTable("PatternSizeYarn");
                });

            modelBuilder.Entity("KnittyGritty.Models.PatternYarn", b =>
                {
                    b.Property<int>("PatternYarnID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatternYarnID"));

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatternID")
                        .HasColumnType("int");

                    b.Property<int>("YarnID")
                        .HasColumnType("int");

                    b.HasKey("PatternYarnID");

                    b.HasIndex("PatternID");

                    b.HasIndex("YarnID");

                    b.ToTable("PatternYarn");
                });

            modelBuilder.Entity("KnittyGritty.Models.Size", b =>
                {
                    b.Property<int>("SizeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SizeID"));

                    b.Property<string>("SizeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SortOrder")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SizeID");

                    b.ToTable("Size");
                });

            modelBuilder.Entity("KnittyGritty.Models.Yarn", b =>
                {
                    b.Property<int>("YarnID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YarnID"));

                    b.Property<string>("FiberContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Meterage")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnitWeight")
                        .HasColumnType("int");

                    b.Property<int>("YarnBrandID")
                        .HasColumnType("int");

                    b.Property<string>("YarnWeight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("YarnID");

                    b.HasIndex("YarnBrandID");

                    b.ToTable("Yarn");
                });

            modelBuilder.Entity("KnittyGritty.Models.YarnBrand", b =>
                {
                    b.Property<int>("YarnBrandID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YarnBrandID"));

                    b.Property<string>("YarnBrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("YarnBrandID");

                    b.ToTable("YarnBrand");
                });

            modelBuilder.Entity("KnittyGritty.Models.Pattern", b =>
                {
                    b.HasOne("KnittyGritty.Models.Designer", "Designer")
                        .WithMany()
                        .HasForeignKey("DesignerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Designer");
                });

            modelBuilder.Entity("KnittyGritty.Models.PatternCategory", b =>
                {
                    b.HasOne("KnittyGritty.Models.Category", "Category")
                        .WithMany("PatternCategories")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnittyGritty.Models.Pattern", "Pattern")
                        .WithMany("PatternCategories")
                        .HasForeignKey("PatternID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Pattern");
                });

            modelBuilder.Entity("KnittyGritty.Models.PatternLanguage", b =>
                {
                    b.HasOne("KnittyGritty.Models.Language", "Language")
                        .WithMany("PatternLanguages")
                        .HasForeignKey("LanguageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnittyGritty.Models.Pattern", "Pattern")
                        .WithMany("PatternLanguages")
                        .HasForeignKey("PatternID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Pattern");
                });

            modelBuilder.Entity("KnittyGritty.Models.PatternSize", b =>
                {
                    b.HasOne("KnittyGritty.Models.Pattern", "Pattern")
                        .WithMany("PatternSizes")
                        .HasForeignKey("PatternID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnittyGritty.Models.Size", "Size")
                        .WithMany("PatternSizes")
                        .HasForeignKey("SizeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pattern");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("KnittyGritty.Models.PatternSizeYarn", b =>
                {
                    b.HasOne("KnittyGritty.Models.Pattern", "Pattern")
                        .WithMany("PatternSizeYarns")
                        .HasForeignKey("PatternID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnittyGritty.Models.Size", "Size")
                        .WithMany("PatternSizeYarns")
                        .HasForeignKey("SizeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnittyGritty.Models.Yarn", "Yarn")
                        .WithMany("PatternSizeYarns")
                        .HasForeignKey("YarnID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pattern");

                    b.Navigation("Size");

                    b.Navigation("Yarn");
                });

            modelBuilder.Entity("KnittyGritty.Models.PatternYarn", b =>
                {
                    b.HasOne("KnittyGritty.Models.Pattern", "Pattern")
                        .WithMany("PatternYarns")
                        .HasForeignKey("PatternID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnittyGritty.Models.Yarn", "Yarn")
                        .WithMany("PatternYarns")
                        .HasForeignKey("YarnID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pattern");

                    b.Navigation("Yarn");
                });

            modelBuilder.Entity("KnittyGritty.Models.Yarn", b =>
                {
                    b.HasOne("KnittyGritty.Models.YarnBrand", "YarnBrand")
                        .WithMany()
                        .HasForeignKey("YarnBrandID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("YarnBrand");
                });

            modelBuilder.Entity("KnittyGritty.Models.Category", b =>
                {
                    b.Navigation("PatternCategories");
                });

            modelBuilder.Entity("KnittyGritty.Models.Language", b =>
                {
                    b.Navigation("PatternLanguages");
                });

            modelBuilder.Entity("KnittyGritty.Models.Pattern", b =>
                {
                    b.Navigation("PatternCategories");

                    b.Navigation("PatternLanguages");

                    b.Navigation("PatternSizeYarns");

                    b.Navigation("PatternSizes");

                    b.Navigation("PatternYarns");
                });

            modelBuilder.Entity("KnittyGritty.Models.Size", b =>
                {
                    b.Navigation("PatternSizeYarns");

                    b.Navigation("PatternSizes");
                });

            modelBuilder.Entity("KnittyGritty.Models.Yarn", b =>
                {
                    b.Navigation("PatternSizeYarns");

                    b.Navigation("PatternYarns");
                });
#pragma warning restore 612, 618
        }
    }
}
